feat: nginx rate limit configurable
decentraland/catalyst-owner pull request #108
Opened 2022-02-04 19:37 UTC by pedrotambo

2022-02-04 20:01 UTC, agusaldasoro requested changes
Can we delete the files `lambdas.conf`, `content.conf`, `comms.conf` & `rates.conf` so we only have the templates on the repository, and the ones used for config are in the `.gitignore`. This way we would avoid editing the wrong file.

2022-02-04 20:01 UTC, agusaldasoro commented on init.sh
> +    generate_nginx_config_files $nginx_server_template_https
nice!

2022-02-04 20:01 UTC, agusaldasoro commented on local/nginx/conf.d/katalyst-http.conf.template
> +    'OPTIONS'   '';
need to sync with base branch

2022-02-07 13:35 UTC, pedrotambo commented on .env-advanced.example
> +RATE_LIMIT_ENABLED=1
👍

2022-02-07 13:37 UTC, pedrotambo commented on .env-advanced.example
> +RATE_LIMIT_NGINX_VAR=http_x_forwarded_for
Yeah... i thought about that, it seemed to me a little redundant to set the config to the default values, as they are set in the `init.sh`. Wouldn't it be better to remove the from the example as they are default values?

2022-02-07 13:37 UTC, pedrotambo commented on README.md
> +| RATE_LIMIT_NGINX_VAR  | This is the variable that nginx will used to limit the requests, see http://nginx.org/en/docs/http/ngx_http_core_module.html#variables for available variables. By default, t
👍

2022-02-07 13:40 UTC, agusaldasoro commented on .env-advanced.example
> +RATE_LIMIT_NGINX_VAR=http_x_forwarded_for
You are right, anyway, I'd prefer to leave it twice and with the same (default) values, as the people using this repository to run a catalyst may not have the full context of what each config is doing and they can make typos.

2022-02-07 14:41 UTC, pedrotambo commented on init.sh
> +  fi
Hmmm don't think so. `sed` with  `>` op directly writes to the `$nginx_content_file`, so leaving the `cp` commands outside the `else` will override the `sed` commands.

2022-02-07 14:42 UTC, pedrotambo commented on init.sh
> +  echo -n " - $nginx_server_file, from template: " ; echo -e "\033[33m ${1} \033[39m"
The name of the template file, i.e., `local/nginx/include/comms.conf.template`.

2022-02-07 14:57 UTC, pedrotambo commented on init.sh
> +  else
good catch

2022-02-07 14:57 UTC, pedrotambo commented on init.sh
> +export nginx_rates_template_file="local/nginx/include/rates.conf.template"
do you mean to use `nginx_rates_file + '.template` and remove `nginx_rates_template_file` var, right? Okay

2022-02-07 18:16 UTC, agusaldasoro approved these changes

2022-02-07 18:50 UTC, merged