fix: new sqs receiver
decentraland/catalyst-owner pull request #191
Opened 2022-12-29 09:10 UTC by HPrivakos

2022-12-29 12:29 UTC, menduz requested changes

2022-12-29 12:29 UTC, menduz commented on receive-sqs.sh
> +        sed -i "s/^#\?DOCKER_TAG.*/DOCKER_TAG=$DOCKER_TAG_CONTENT/g" .env
can you replace the `sed` by `echo >>` to append at the end? so we don't lose the history in case of manual rollback

2022-12-29 14:03 UTC, hugoArregui commented on receive-sqs.sh
> +      DOCKER_TAG_LIGHTOUSE=$(echo $BODY | jq -r '.lighthouse');
there is a typo in the var name, LIGHTHOUSE

2023-01-26 12:24 UTC, hugoArregui approved these changes

2023-09-08 20:44 UTC, closed without merging